cmake_minimum_required(VERSION 2.8)
macro(cujak_cuda_test name type src)
    set(test_name TEST_${name}_${type})
    cuda_add_executable(${test_name} ${src})
    target_link_libraries(${test_name} ${ARGN})
    add_test(${test_name} ${CMAKE_CURRENT_BINARY_DIR}/${test_name})
    add_dependencies(build_test ${test_name})
    unset(test_name)
endmacro(cujak_cuda_test)
